// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { CreateRecruitmentData, CreateRecruitmentError, CreateRecruitmentResponse2, SignInData, SignInError, SignInResponse, GetStaticError, GetStaticResponse, SearchRecruitmentsData, SearchRecruitmentsError, SearchRecruitmentsResponse } from './types.gen';

export const client = createClient(createConfig());

export const createRecruitment = <ThrowOnError extends boolean = false>(options: Options<CreateRecruitmentData, ThrowOnError>) => { return (options?.client ?? client).post<CreateRecruitmentResponse2, CreateRecruitmentError, ThrowOnError>({
    ...options,
    url: '/api/v1/recruitments'
}); };

export const signIn = <ThrowOnError extends boolean = false>(options: Options<SignInData, ThrowOnError>) => { return (options?.client ?? client).post<SignInResponse, SignInError, ThrowOnError>({
    ...options,
    url: '/api/v1/accounts/sign-in'
}); };

export const getStatic = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetStaticResponse, GetStaticError, ThrowOnError>({
    ...options,
    url: '/api/v1/static'
}); };

export const searchRecruitments = <ThrowOnError extends boolean = false>(options: Options<SearchRecruitmentsData, ThrowOnError>) => { return (options?.client ?? client).get<SearchRecruitmentsResponse, SearchRecruitmentsError, ThrowOnError>({
    ...options,
    url: '/api/v1/recruitments/search'
}); };